#!/bin/sh

super + Return
	alacritty

super + @space
	alacritty -e tmux new-session -A -s main

super + r
	dmenu_run -b -fn Iosevka

super + p
	passmenu --type -b -fn Iosevka

super + alt + r
	reboot

super + alt + s
	poweroff

super + Escape
	pkill -USR1 -x sxhkd

super + alt + Escape
	bspc wm -r

super + {_,shift + }q
	bspc node -{c,k}

super + {t,s,f}
	bspc node -t {tiled,floating -g sticky,fullscreen}

super + S
	bspc node -g sticky

super + h
	bspc node biggest.local -s focused

super + n
	bspc node -f next.local.leaf.!sticky

super + h
	bspc desktop -l next

super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}
