[font]
size = 11.0

[font.bold]
family = "Iosevka Fixed"

[font.bold_italic]
family = "Iosevka Fixed"

[font.italic]
family = "Iosevka Fixed"

[font.normal]
family = "Iosevka Fixed"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
